<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="https://github.com/tracee/tracee"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  name="HelloWorldService"
                  targetNamespace="https://github.com/tracee/tracee">

    <wsdl:message name="SayHelloRequest">
        <wsdl:part name="firstName" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="SayHelloResponse">
        <wsdl:part name="greeting" type="xsd:string"/>
    </wsdl:message>

    <wsdl:portType name="HelloWorld_PortType">
        <wsdl:operation name="sayHelloWorld">
            <wsdl:input message="tns:SayHelloRequest" name="SayHelloRequest"/>
            <wsdl:output message="tns:SayHelloResponse" name="SayHelloResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="HelloWorld_Binding" type="tns:HelloWorld_PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sayHelloWorld">
            <soap:operation soapAction="sayHelloWorld"/>
            <wsdl:input name="SayHelloRequest">
                <soap:body use="literal" namespace="tns"/>
            </wsdl:input>
            <wsdl:output name="SayHelloResponse">
                <soap:body use="literal" namespace="tns"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="HelloWorld_Service">
        <wsdl:documentation>WSDL File for HelloWorldService</wsdl:documentation>
        <wsdl:port binding="tns:HelloWorld_Binding" name="HelloWorld_Port">
            <soap:address location="local://localPath"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
