package io.tracee;

import io.tracee.configuration.TraceeFilterConfiguration;

import java.util.Map;

/**
 * A backend is expected to be thread-safe (reads and writes are delegated to thread local state).
 */
public interface TraceeBackend {

	/**
	 * Gets the TraceeFilterConfiguration for a given profile.
	 */
	TraceeFilterConfiguration getConfiguration(String profileName);

	/**
	 * Gets the default TraceeFilterConfiguration.
	 */
	TraceeFilterConfiguration getConfiguration();

    /**
     * @param key a non-null identifier.
     * @return {@code true} if this backend contains an entry for the given key. {@code false} otherwise.
     */
    boolean containsKey(String key);

    /**
     * Gets the value for a given key from this backend.
     * @param key a non-null identifier.
     * @return the stored value or {@code null} if not present.
     */
    String get(String key);

	int size();

	/**
	 * Clears all context information from this backend.
	 */
	void clear();

    /**
     * @return {@code true} if this backend contains no context information, {@code false} otherwise.
     */
    boolean isEmpty();

    /**
     * Puts a key/value into this backend.
     * @param key   the key of the tuple
     * @param value the value of the tuple
	 * @throws java.lang.NullPointerException if key or value is {@code null}
     */
    void put(String key, String value);

    void putAll(Map<? extends String, ? extends String> m);

	/**
	 * Generates a copy of the TraceeBackend. All keys known by TracEE are fetched from underlying MDC and copied to
	 * this map.
	 * @return immutable copy of the current state of the backend
	 */
	Map<String, String> copyToMap();

    /**
     * Removes the entry with the given key from this backend. Does nothing if the key is {@code null} or not found.
     * @param key ignored if {@code null}
     */
    void remove(String key);

	/**
	 * Shortcut for {@code get(TraceeConstants.INVOCATION_ID_KEY)}. This ID could be {@code null} if the incoming call haven't generated a invocationId.
	 * @return The current value for the Key {@link io.tracee.TraceeConstants#INVOCATION_ID_KEY} or {@code null} if no value is set.
	 */
	String getInvocationId();

	/**
	 * Shortcut for {@code get(TraceeConstants.SESSION_ID_KEY)}. A sessionId is only generated by the servlet-binding or by the application itself.
	 * If no sessionID has been generated this method returns {@code null}.
	 * @return The current value for the Key {@link io.tracee.TraceeConstants#SESSION_ID_KEY} or {@code null} if no value is set.
	 */
	String getSessionId();
}
