# JBoss7 with deployed tracee-examples-jaxws and tracee-examples-ejb
#
# VERSION       1.0

FROM dockerfile/elasticsearch
MAINTAINER Daniel Wegener "daniel.wegener@holisticon.de"

ADD elasticsearch.yml /etc/elasticsearch/
ADD logging.yml /etc/elasticsearch/

ENTRYPOINT []