# JBoss7 with deployed tracee-examples-jaxws and tracee-examples-ejb
#
# VERSION       1.0

FROM dockerfile/mongodb
MAINTAINER Daniel Wegener "daniel.wegener@holisticon.de"

ENTRYPOINT ["mongod","--smallfiles", "--rest"]